### ISSUE TITLE
FlashCards Deck-Creator

### ISSUE THREAD

**Issue by Dennis2512** [Dennis2512/ffc#4]
Add the possibility to create your own decks on the website.

**Comment by nikolockenvitz** [comment]
Checkout https://github.com/fancy-flashcard/ffc/issues/40 for a nice idea related to deck creation.

**Comment by Dennis2512** [comment]
**ToDo:**

- [ ] CardDeckCreator.vue: saveCards()
Description: All created, not empty cards should be saved as card deck by pressing the green button on the right bottom. After clicking the save button, it should download the created deck. The page should be closed and the home page should be visible afterwards.

- [ ] CardDeckCreator.vue: addNewCard()
Description: Dynamically add a new card by pressing the green floating action button on the left bottom. A new card should be a DynamicCard.vue component with increasing number in it`s v-card-title.

- [ ] DynamicCard.vue: deleteCard()
Description: By pressing the red trash bin button on the cards right side, the card should be removed. The card number should change dynamically for all following cards (decrease all following card numbers by one). 

- [ ] CardDeckCredentials.vue: Make certain textfields mendatory
Description: Textfields have to be mandatory (only uuid-field has to be optional). By running the saveCards() method in CardDeckCreator.vue it should test if all mendatory fields are filled. If not, the user should be informed by any kind of pop up.

- [ ] Optional: Import and edit existent card decks
